FitClubCMS/FitClubCMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

# adding static() helper function to server django media fileswith the Django development server 
#during development (that is when the DEBUG setting is set to True).
# Only suitable for development environment not production
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

FitClubCMS/accounts/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from . import views

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("", views.landing_page, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("packages/", views.packages, name="packages"),
    path("my_package/", views.my_package, name="my_package"),
    path("trainers/", views.trainers, name="trainers"),
    path("schedule/", views.schedule, name="schedule"),
    path("all_events/", views.all_events, name="all_events"),
    path("add_event/", views.add_event, name="add_event"),
    path("update_event/", views.update_event, name="update_event"),
    path("remove_event/", views.remove_event, name="remove_event"),
    path("payment_index/", views.payment_index, name="payment_index"),
    path("payment_form/", views.payment_form, name="payment_form"),
    path("payment_success_page/", views.payment_success_page, name="payment_success"),
    path("sessions_list/", views.sessions_list, name="sessions_list"),
    path("add_session/", views.add_session, name="add_session"),
    path("book_session/", views.book_session, name="book_session"),
    path("my_bookings/", views.my_bookings, name="my_bookings"),
    path(
        "cancel_booking/<int:booking_id>/", views.cancel_booking, name="cancel_booking"
    ),
    path("payment_history/", views.payment_history, name="payment_history"),
    path("send_email/", views.send_email, name="send_email"),
    path("payment_result/", views.payment_result, name="payment_result"),
]

FitClubCMS/accounts/models.py
from datetime import date, datetime, timedelta

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Package(models.Model):
    package_id = models.AutoField(primary_key=True)
    package_name = models.CharField(max_length=255, default=None)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    package_photo = models.ImageField(upload_to="site/%Y/%m/%d/", blank=True)

    def __str__(self):
        return self.package_name


class Profile(models.Model):
    CHOICES = [("Male", "Male"), ("Female", "Female")]
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    last_name = models.CharField(max_length=50)
    phone_no = models.CharField(max_length=12)
    address = models.CharField(max_length=256, null=True)
    sex = models.CharField(max_length=10, choices=CHOICES)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True)
    package = models.ForeignKey(
        "Package",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def clean(self):
        if self.date_of_birth is not None:
            today = date.today()
            min_date = today - timedelta(
                days=365 * 10
            )  # Minimum date resulting in an age of 10 years
            if self.date_of_birth > min_date:
                raise ValidationError("Your age must at least be 10 year!")

    def __str__(self):
        return f"Profile of {self.user.username}"


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_or_save_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Transaction(models.Model):
    transaction_id = models.AutoField(primary_key=True)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    package = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    transaction_date = models.DateTimeField()
    status = models.CharField(max_length=255)
    receipt_no = models.CharField(max_length=256, blank=True, null=True)
    sender_no = models.CharField(max_length=15)

    def __str__(self):
        return f"Transaction {self.transaction_id}"


class Trainers(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    trainer_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    specialization = models.TextField(null=True, blank=True)
    experience = models.DecimalField(max_digits=3, decimal_places=1, null=True, blank=True)

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = "Trainers"  # prevents the addition of (S) in the admin section
        verbose_name_plural = "Trainers"
        db_table = "trainers"


# Schedule model
class Events(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    start = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True)
    trainer = models.ForeignKey(
        Trainers, on_delete=models.SET_NULL, null=True, blank=True
    )

    class Meta:
        verbose_name = "Events"
        verbose_name_plural = "Events"
        db_table = "events"


class Booking(models.Model):
    booking_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    start = models.CharField(max_length=20)
    end = models.CharField(max_length=20)
    trainer = models.CharField(max_length=100)
    book_time = models.DateTimeField(auto_now=True)


class Sessions(models.Model):
    session_name = models.CharField(max_length=255)
    start = models.DateTimeField()
    end = models.DateTimeField()
    trainer = models.CharField(max_length=255)

    def __str__(self):
        return self.id

    class Meta:
        verbose_name = "Session"
        verbose_name_plural = "Sessions"
        db_table = "sessions"


class Email(models.Model):
    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sent_emails"
    )
    recipient = models.EmailField(default=settings.EMAIL_HOST_USER)
    subject = models.CharField(max_length=255)
    content = models.TextField()
    sent_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"From: {self.sender.email} | To: {self.recipient} | Subject: {self.subject}"  # return self.subject

FitClubCMS/accounts/views.py
import email
import functools
import imaplib
import json
from datetime import date, datetime, timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core import serializers
from django.core.cache import cache
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.db import IntegrityError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.utils.dateparse import parse_datetime
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django_daraja.mpesa.core import MpesaClient

from .forms import (
    LoginForm,
    ProfileEditForm,
    ReplyEmailForm,
    SessionForm,
    UserEditForm,
    UserRegistrationForm,
)
from .models import Booking, Email, Events, Package, Profile, Trainers, Transaction


def landing_page(request):
    return render(request, "accounts/pages/landingpage.html")


from django.shortcuts import redirect
from django.urls import reverse


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd["username"], password=cd["password"]
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                else:
                    return HttpResponse("Disabled Account")
            else:
                return HttpResponse("Invalid Login")
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form})


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user but avoid saving it yet
            new_user = user_form.save(commit=False)
            # set the chosen password
            new_user.set_password(user_form.cleaned_data["password"])
            # save user object
            new_user.save()
            return render(
                request, "accounts/register_done.html", {"new_user": new_user}
            )
    else:
        user_form = UserRegistrationForm()
    return render(request, "accounts/register.html", {"user_form": user_form})


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile, data=request.POST, files=request.FILES
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile updated successfully")
        else:
            messages.error(request, "Error updating your profile")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(
        request,
        "accounts/edit.html",
        {"user_form": user_form, "profile_form": profile_form},
    )


@login_required
def payment_form(request):
    # Retrieve the package data from the database or any other source
    package_id = request.GET.get("package_id")
    package = get_object_or_404(Package, pk=package_id)

    context = {"package": package}
    return render(request, "accounts/pages/payment_form.html", context)


@csrf_exempt
@login_required
def payment_index(request):
    if request.method == "POST":
        # Retrieve the form data
        amount = float(request.POST.get("amount"))
        amount = round(
            amount
        )  # Convert to integer by rounding to the nearest whole number
        phone_number = request.POST.get("phone_no")
        package_name = request.POST.get("package_name")
        package_id = request.POST.get("package_no")

        user = request.user
        # storing the two in order to be accessed from the response in payment_result
        cache.set("package_name", package_name)
        cache.set("user", user)
        cache.set("package_id", package_id)

        print(package_name)
        print(user)

        cl = MpesaClient()
        account_reference = "reference"
        transaction_desc = "Description"
        callback_url = "https://52f1-41-89-10-241.ngrok-free.app/payment_result/"
        response = cl.stk_push(
            phone_number, amount, account_reference, transaction_desc, callback_url
        )

        return redirect("payment_success")

    return HttpResponse(response)


@csrf_exempt
def payment_result(request):
    print("Response returned")
    cl = MpesaClient()
    if request.method == "POST":
        result = cl.parse_stk_result(request.body)
        if result["ResultCode"] == 0:
            amount = result.get("Amount")
            receipt_no = result.get("MpesaReceiptNumber")
            transaction_date = result.get("TransactionDate")
            phone_number = result.get("PhoneNumber")

            print(amount)
            print(receipt_no)
            print(transaction_date)
            print(phone_number)
            print(type(phone_number))

            number = str(phone_number)
            print(type(number))
            transaction_date_str = str(transaction_date)
            transaction_date = datetime.strptime(transaction_date_str, "%Y%m%d%H%M%S")
            print(transaction_date)

            phone_number_str = str(type(phone_number))
            # Retrieve the package_name and username from the session
            user = cache.get("user")
            package_name = cache.get("package_name")
            package_id = cache.get("package_id")

            print(package_name)
            print(user)
            print(package_id)

            # create transaction object to save the transaction into the database
            transaction = Transaction.objects.create(
                amount=amount,
                package=package_name,
                user=user,
                transaction_date=transaction_date,
                status="Complete",
                receipt_no=receipt_no,
                sender_no=number,
            )

            # retrieve the with the given package_id
            package = get_object_or_404(Package, pk=package_id)

            print(package)

            # update the package name of the user in profile
            profile = user.profile
            profile.package = package
            profile.save()

            user = cache.delete("user")
            package_name = cache.delete("package_name")
            package_id = cache.delete("package_id")

    return HttpResponse("okay")


@login_required
def payment_success_page(request):
    return render(request, "accounts/pages/payment_success.html")


@login_required
def dashboard(request):
    context = {}
    if request.user.is_authenticated:
        context["date_today"] = date.today()
        context["current_time"] = datetime.now().strftime("%H:%M:%S")

        current_datetime = timezone.now()

        total_bookings = Booking.objects.filter(user=request.user).count()
        context["total_bookings"] = total_bookings

        # Find the next session booking that hasn't started yet
        next_session = (
            Booking.objects.filter(
                user=request.user,
                start__gt=current_datetime,
            )
            .order_by("start")
            .first()
        )

        # Get the start time and day of the next session
        if next_session:
            next_session_start_str = next_session.start
            next_session_start = datetime.strptime(
                next_session_start_str, "%Y-%m-%d %H:%M:%S"
            )
            next_session_date = next_session_start.date()
            next_session_time = next_session_start.strftime("%I:%M %p")

            if next_session_date == date.today():
                day_indicator = "Today"
            else:
                day_indicator = day_indicator = next_session_date.strftime(
                    "%A"
                )  # Format the day of the week
            context["next_session_start"] = f"{day_indicator} at {next_session_time}"
        else:
            context["next_session_start"] = "No upcoming sessions"

        try:
            profile = Profile.objects.get(user=request.user)
            context["profile"] = profile
            context["user"] = request.user

            # Check if the profile has a package
            if profile.package:
                context["package_name"] = profile.package.package_name
            else:
                context["package_name"] = None

        except Profile.DoesNotExist:
            context["package_name"] = None

        # Retrieve the account status and last login information
        user = User.objects.get(pk=request.user.pk)
        context["account_status"] = user.is_active
        context["last_login"] = user.last_login
        context["date_joined"] = user.date_joined

        # Retrieve the total count of transactions made by the logged-in user
        total_transactions = Transaction.objects.filter(user=request.user).count()
        context["total_transactions"] = total_transactions

        # Retrieve the most recent transaction associated with the logged-in user
        recent_transaction = (
            Transaction.objects.filter(user=request.user)
            .order_by("-transaction_date")
            .first()
        )
        if recent_transaction:
            transaction_date = recent_transaction.transaction_date
            expiry_date = transaction_date + timedelta(days=30)

FitClubCMS/accounts/templates/accounts/pages/booking_form.html
{% extends 'base2.html' %} {% block title %} {% endblock %} {% block content %}
<!-- {% if messages %}
<div class="messages">
  {% for message in messages %}
  <div class="message {{ message.tags }}">
    <span class="message-text">{{ message }}</span>
    <button class="close-button">&times;</button>
  </div>
  {% endfor %}
</div>
{% endif %} -->
{% include 'accounts/components/messages.html' %}

<table>
  <h4>Available Sessions for Booking</h4>
  <thead>
    <tr>
      <th>Session Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Trainer</th>
      <th>Booking Status</th>
    </tr>
  </thead>
  <tbody>
    {% for event in events %}

    <tr>
      <form method="POST" class="booking-form" action="{% url 'book_session'%}">
        {% csrf_token %}
        <input type="hidden" name="event_name" value="{{ event.name}}" >
        <input type="hidden" name="event_start" value="{{ event.start|date:"Y-m-d H:i:s"}}">
        <input type="hidden" name="event_end" value="{{ event.end|date:"Y-m-d H:i:s" }}">
        <input type="hidden" name="event_trainer" value="{{ event.trainer }}">

        <td>{{ event.name }}</td>
        <td>{{ event.start}}</td>
        <td>{{ event.end}}</td>
        <td>{{ event.trainer }}</td>
        <td><input type="submit" value="Book" class="custom-button" /></td>
      </form>
    </tr>

    {% endfor %}
  </tbody>
</table>

<div class="my-bookings mt-5">
  <h4>Active Bookings</h4>
  <table id="bookings-table">
    <thead>
      <tr>
        <th>Booking ID</th>
        <th>Session Name</th>
        <th>Time Left</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>

<script>
// Remove the message box when the close button is clicked
const closeButton = document.querySelector('.close-button');
closeButton.addEventListener('click', function() {
  const messageBox = this.closest('.message');
  messageBox.remove();
  });

</script>

{% endblock %}

FitClubCMS/accounts/templates/accounts/pages/dashboard.html
{% extends "base2.html" %}
{% load static %}

{% block title %} {% endblock %}

{% block content %}
<h4>My Dashboard </h4>

<div class="dashboard-cont">
  
  <div class="biodata mt-4">
    <form>
      {% if request.user.is_authenticated %}

          <input type="text" name="time" id="current-time" readonly disabled>
          <input type="text" name="day" value="{{ date_today|date:'D' }}" readonly disabled>
          <input type="text" name="month" value="{{ date_today|date:'M' }}" readonly disabled>
          <input type="text" name="date" value="{{ date_today|date:'Y-m-d' }}" readonly disabled>
      
    </form>
    <!-- Add the notification bell icon -->
   
      <!-- <div class="notification-bell">
        <i class="fa-solid fa-bell fa-2x"></i>
        <span class="notification-count">{{ total_notifications }} Email Notifications</span>
      </div> -->

     {% endif %} 
   </div>

  </div>


 

   <div class="quick-access mt-4 mb-4">
    <div class="row justify-content-around mx-auto">

      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <i class="fa-solid fa-book-open-reader fa-3x custom-icon-color"></i>
            <h5 class="card-title">Session Bookings</h5>
            <p class="card-text">All Bookings {{ total_bookings }} </p>
            <p class="card-text">Next Session  {{ next_session_start }}</p>
            <a href="{% url 'sessions_list' %}" class="btn btn-success">Active Bookings</a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <i class="fa-solid fa-dumbbell fa-3x custom-icon-color"></i>
            <h5 class="card-title">My Package</h5>
            <p class="card-text">Current Package: {% if package_name %}{{ package_name }}{% else %}Not Enrolled Yet{% endif %}</p></p>
            <p class="card-text">Subscription Expires on  {% if expiry_date %}{{ expiry_date }}{% else %}N/A{% endif %}</p>
            <a href="{% url 'my_package'%}" class="btn btn-success">Package Details</a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <i class="fa-solid fa-coins fa-3x custom-icon-color"></i>
            <h5 class="card-title">Payments</h5>
            <p class="card-text">Total payments made {{ total_transactions }}</p><br>
            <a href="{% url 'payment_history' %}" class="btn btn-success">View Records</a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
            <i class="fa-solid fa-user-tag fa-3x custom-icon-color"></i>
            <h5 class="card-title">Account Profile</h5>
            <p class="card-text">Status: {% if account_status %}Active{% else %}Inactive{% endif %}</p>
            <p class="card-text">Last login {% if last_login %}{{ last_login }}{% else %}N/A{% endif %} </p>
            <a href="{% url 'edit' %}" class="btn btn-success">Update Profile</a>
          </div>
        </div>
      </div>

    </div>
    
   </div>


  <div class="personalized-info"> 

    {% include 'accounts/components/messages.html' %}

   <div class="feed-form">
    {% include 'accounts/components/messages.html' %}

    <form method="post" class="email-form" action="{% url 'send_email' %}">
      {% csrf_token %}
      <h3>Feedback and Queries</h3>
      {% if request.user.is_authenticated %}

      <div class="form-group">
        <label for="id_subject">Subject:</label>
        <input type="text" class="form-control" id="id_subject" name="subject" required>
      </div>
      <div class="form-group">
        <label for="id_content">Content:</label>
        <textarea class="form-control" id="id_content" rows="4" name="content" required></textarea>
      </div>
      <input type="submit" class="custom-button" value="Send Email">
      <hr>
      <h3>Email or Call Directly</h3><br>
      <div class="icon"><i class="fa-solid fa-envelope"></i><span><a href="mailto:brianaweyo23@gmail.com">  brianaweyo23@gmail.com</a></span></div> <br>
      <div class="icon"><i class="fa-solid fa-phone-volume"></i><span><a href="tel:+07595449949849">  07595449949849</a></span></div>
      {% endif %}

    </form> 

    <div class="profile-overview">
      

      <div class="row">
        <div class="col"><img src="{{ photo_url }}" class="rounded float-left img-fluid  mt-5" alt="profile picture" style="width: 200px; height: 200px; padding-left: .5rem;"></div>
        <div class="col">
          
          <div class="form-outline">
            <input type="text" class="form-control mt-5" value="{{ user.first_name|title }}" readonly />
            <label class="form-label">Firstname</label>
          </div>
        </div>
        <div class="col">
       
          <div class="form-outline">
            <input type="email" class="form-control mt-5 " value="{{ profile.last_name|title }}" readonly  />
            <label class="form-label">Last Name</label>
          </div>
        </div>
      </div>
      
      <hr />
      
      <div class="row">
        <div class="col">
   
          <div class="form-outline">
            <input type="text" id="form8Example3" class="form-control" value="{{ profile.date_of_birth }}" readonly />
            <label class="form-label" for="form8Example3">Date of Birth</label>
          </div>
        </div>
        <div class="col">
          
          <div class="form-outline">
            <input type="text"  class="form-control" value="{{ profile.sex|title }}" readonly />
            <label class="form-label">Gender</label>
          </div>
        </div>
        <div class="col">
        
          <div class="form-outline">
            <input type="email" class="form-control" value="{{ user.email }}" readonly />
            <label class="form-label">Email address</label>
          </div>
        </div>
      </div>

      <hr />

      <div class="row">
        <div class="col">
        
          <div class="form-outline">
            <input type="text"  class="form-control" value="{{ profile.phone_no }}" readonly />
            <label class="form-label" >Phone Number</label>
          </div>
        </div>
        <div class="col">

          <div class="form-outline">
            <input type="text"  class="form-control" value="{{ profile.address }}" readonly />
            <label class="form-label">Address</label>
          </div>
        </div>
        <div class="col">
          <div class="form-outline">
            <input type="text" class="form-control" value="{{ last_login }}" readonly />
            <label class="form-label">Joined Date</label>
          </div>
        </div>
      </div>
      
     </div>

  </div>
</div>



{% endblock %}

FitClubCMS/accounts/templates/accounts/pages/my_package.html
{% extends "base2.html" %}
{% load static %}
{% block title %} {% endblock %}
{% block styles %} 
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >
 <link href="{% static 'accounts/css/profile.css' %}" rel="stylesheet">
 <!-- <link href="{% static 'accounts/css/forms.css' %}" rel="stylesheet"> -->
{% endblock styles %}

{% block content %}
 
<h4>My Package Subscription Details </h4>
 
 <div class="package-descr">

        <div class="card my-package-card" style="width: 18rem;">
            <img src="{{ package.package_photo.url }}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{ package.package_name }}</h5>
              <p class="card-text">{{ package.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
              <!-- <li class="list-group-item">Cras justo odio</li> -->
            </ul>
            <div class="card-body">
              <a href="{% url 'payment_form' %}?package_id={{ package.package_id }}" class="card-link">Renew</a>
              <div class="cost">Ksh {{ package.price }}</div>
            </div>
          </div>

     <div class="descr-cont">
        

            <div class="profile-overview">
      

              <div class="row">
                <div class="col">
                    <img src="{{ package.photo }}" class="rounded float-left img-fluid mt-5" alt="profile picture" style="width: 200px; height: 200px; padding-left: .5rem;">
                </div>
                <div class="col">
                    <div class="form-outline">
                        <input type="text" class="form-control mt-5" value="{{ recent_transaction.transaction_date }}" readonly>
                        <label class="form-label">Subscription Date</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <input type="email" class="form-control mt-5" value="{{ recent_transaction.transaction_date|date:"F d, Y" }}" readonly>
                        <label class="form-label">Subscription Expiry</label>
                    </div>
                </div>
            </div>
            
            <hr />
            
            <div class="row">
                <div class="col">
                    <div class="form-outline">
                        <input type="text" id="form8Example3" class="form-control" value="{{ package.package_name }}" readonly>
                        <label class="form-label" for="form8Example3">Package Name</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <input type="text" class="form-control" value="{{ remaining_days }}" readonly>
                        <label class="form-label">Remaining Days</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <input type="email" class="form-control" value="{{ recent_transaction.amount }}" readonly>
                        <label class="form-label">Amount Paid(Ksh)</label>
                    </div>
                </div>
            </div>
            
            <hr />
            
            <div class="row">
              <div class="col">
                <div class="form-outline">
                    <a href="{% url 'packages' %}" class="btn btn-primary" role="button">Upgrade</a>
                </div>
            </div>
            <div class="col">
                <div class="form-outline">
                  <a href="{% url 'payment_form' %}?package_id={{ package.package_id }}" class="btn btn-primary" role="button">Renew</a>
                </div>
            </div>
                <div class="col">
                    <div class="form-outline">
                        <input type="text" class="form-control" value="{{ package.description }}" readonly>
                        <label class="form-label">Package Description</label>
                    </div>
                </div>
            </div>
            
     

      </div>  

{% endblock %}

FitClubCMS/accounts/templates/accounts/pages/payment_records.html
{% extends 'base2.html' %} {% block title %}{% endblock %} {% block content %}

<table>
  <h4>My Payments History</h4>
  <thead>
    <tr>
      <th>Tranasaction Id</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Receipt No</th>
      <th>Phone</th>
      <th>Package</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    {% for transaction in transactions %}

    <tr>
      <td>{{ transaction.transaction_id }}</td>
      <td>{{ transaction.transaction_date }}</td>
      <td>{{ transaction.amount }}</td>
      <td>{{ transaction.receipt_no }}</td>
      <td>{{ transaction.sender_no }}</td>
      <td>{{ transaction.package }}</td>
      <td>{{ transaction.status }}</td>
    </tr>

    {% endfor %}
  </tbody>
</table>
{% endblock %}

FitClubCMS/accounts/templates/accounts/pages/payment_success.html
{% extends 'base2.html' %}

{% block title %}  {% endblock %}

{% block content %}
 
<div class="notification">
  <h1>Your payment has been successfully submittted for processing!</h1>
  <p>You can view your payment records <a href="{% url 'payment_history' %}">here</a> for updated payment records.</p>
  <p>Go back to your <a href="{% url 'dashboard' %}">dashboard</a>.</p>
</div>

{% endblock%}